# Computer Networks Project
# Mac 1 - Private DNS

port=53
listen-address=127.0.0.1,10.7.26.144
bind-interfaces

domain-needed
bogus-priv

# Project services
# Replace 10.7.6.173 with the actual Mac 2 IP
address=/app.team1.test/10.7.6.173
address=/api.team1.test/10.7.6.173

# DNS cache
local-ttl=30
cache-size=1000

# Logging
log-queries
log-facility=/tmp/dnsmasq.log
